# 依赖metrics-server
# kubectl run nginx  --image=nginx:1.14-alpine -n dev --requests=cpu=100m -n dev  # 有待研究【--requests=cpu=100m】
# kubectl expose deploy nginx --name=svc-nginx --type=NodePort --port=80  -n dev
# kubectl get hpa hpaname -n dev -w
# 用postman 对service Ip 做压力测试
apiVersion: autoscaling/v1 #版本号
kind: HorizontalPodAutoscaler #类型
metadata: #元数据
  name: hpaname
  namespace: dev #所属命名空间
  labels: #标签
    contro: hpa-contro
spec:
  minReplicas: 1 #最小pod数量
  maxReplicas: 10 #大嘴Pod数量
  targetCPUUtilizationPercentage: 3 #CPU使用率指标
  scaleTargetRef: #指定要控制的deployment信息
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
