server:
  port: 8888
logging:
  config: classpath:log4j2.xml

spring:   # spring boot admin
  boot:
    admin:
      client:
        url:
          - http://192.168.88.1:9999 #注册到server统一管理，访问server端查看监控http://192.168.88.1:9999/applications

# actuator 配置
management:
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    info:
      enabled: true
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - "*"
    enabled-by-default: true
#    jmx:
#      exposure:
#        include:
#          - "*"
info: #用于显示整个系统的一些介绍信息
  appConfig: @profile.active@
  appName: @artifactId@
  encode: @project.build.sourceEncoding@
  author: eric


