apiVersion: apps/v1 #版本号
kind: ReplicaSet #类型
metadata: #元数据
  name: rsname #pod控制器名称
  namespace: dev #所属命名空间
  labels: #标签
    contro: rs-contro
spec: #规范相信
  replicas: 1 #副本数量
  selector: #选择器
    matchLabels: #匹配那些Pod
      app: nginx-pod
  template: #模版。当副本数量不足时，会根据模版创建Pod
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.1
