#环境准备
#https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.30.0/deploy/static/mandatory.yaml
#https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.30.0/deploy/static/provider/baremetal/service-nodeport.yaml
# 查看ingress环境
# kubectl get svc -n ingress-nginx -o wide -w
# kubectl  get deploy -n ingress-nginx -w

#证书生成
#openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/C=CN/ST=BJ/L=BJ/O=nginx/CN=www.eric.com"
#openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/C=CN/ST=BJ/L=BJ/O=nginx/CN=www.liyaqiu.com"
#创建密钥
#kubectl create secret tls tls-eric-secret --key tls.key --cert tls.crt
#kubectl create secret tls tls-liyaqiu-secret --key tls.key --cert tls.crt

apiVersion: extensions/v1beta1 #必选
kind: Ingress #必选
metadata: #必选
  name: ingress-https-name #必选 pod名称
  namespace: dev # pod所属命名空间 (默认 default)
  labels:
    ver: snapshot-1.0
    env: test
spec:
  tls:
    - hosts:
        - www.eric.com
      secretName: tls-eric-secret
    - hosts:
        - www.liyaqiu.com
      secretName: tls-liyaqiu-secret
  rules:
    - host: www.eric.com
      http:
        paths:
          - path: /
            backend:
              serviceName: svc-nginx-headless
              servicePort: 9999 #只关联到svc的port，此prot一定要和svc port对应上
    - host: www.liyaqiu.com
      http:
        paths:
          - path: /
            backend:
              serviceName: svc-tomcat-headless
              servicePort: 8888 #只关联到svc的port，此prot一定要和svc port对应上
