apiVersion: v1 #必选
kind: Pod #必选
metadata: #必选
  name: test-pod #必选 pod名称
  namespace: pro # pod所属命名空间 (默认 default)
  labels:
    ver: snapshot-1.0
    env: test
spec: #必选 pod中容器的规范
  containers: #必选,pod容器列表
    - name: busybox-containers
      image: test:v1
      command: ["tail","-f","/etc/shadow"] #跟docket entrypoint一样功能
      ports: #需要暴露的端口列表
        - name: nginx-prot #端口名
          containerPort: 90 #容器端口