apiVersion: apps/v1 #版本号
kind: DaemonSet #类型
metadata: #元数据
  name: dsname #pod控制器名称
  namespace: dev #所属命名空间
  labels: #标签
    contro: ds-contro
spec: #规范信息
  revisionHistoryLimit: 3 #保留历史版本
  updateStrategy: #更新策略
    #方式1（先删除，后启动）
    #type: OnDelete
    #方式2（先启动，后删除）
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 #(默认为1)，逐个node创建pod后在删除pod，如果设置为30%，多个节点同时先启动pod后删除pod
  selector: #选择器
    matchLabels: #匹配Pod
      app: nginx-pod
    matchExpressions: #表达式匹配Pod
      - key: app
        operator: In # In,NotIn,Exists,DoesNotExist
        values: [nginx-pod,aa,bb]
  template: #模版。当副本数量不足时，会根据模版创建Pod
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.1
          ports:
            - containerPort: 80
