server:
  port: 8083
spring:
  application:
    name: sp-b-service
  cloud:
    nacos:
      server-addr: 192.168.109.1:8848
      discovery:
        cluster-name: lianjiang
    sentinel:
      transport:
        dashboard: localhost:8080
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
logging:
  config: classpath:log4j2.xml