spring:
  application:
    name: service-msm
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 192.168.88.10:8848
      discovery:
        cluster-name: hangzhou
        ephemeral: true #默认为true 临时实例，靠客户端去做心跳，false为永久实例，nacos发心跳到客户端
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #对json返回时间进行格式化
    time-zone: GMT+8


logging:
  #引入文件方式
  config: classpath:log4j2.xml