server:
  port: 8080

# 单机普通配置
spring:
  redis:
    database: 0
    host: 192.168.88.11
    port: 6661
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

# 哨兵集群
#spring:
#  redis:
#    password: 123456
#    database: 1
#    lettuce:
#      pool:
#        max-active: 8
#        min-idle: 0
#        max-wait: -1ms
#        max-idle: 8
#    sentinel:
#      master: mymaster
#      nodes:
#        - 192.168.88.11:9991
#        - 192.168.88.11:9992
#        - 192.168.88.11:9993

# 分片集群
#spring:
#  redis:
#    password: 123456
#    cluster:
#      max-redirects: 3
#      nodes:
#        - 192.168.88.11:8881
#        - 192.168.88.11:8882
#        - 192.168.88.11:8883
#        - 192.168.88.11:8884
#        - 192.168.88.11:8885
#        - 192.168.88.11:8886
#    lettuce:
#      pool:
#        max-active: 8
#        min-idle: 0
#        max-wait: -1ms
#        max-idle: 8
#      cluster:
#        refresh:
#          adaptive: true #集群有master宕机，用于动态发现并刷新集群拓扑
#          period: 2000
