apiVersion: v1 #必选
kind: Pod #必选
metadata: #必选
  name: mypod-demo2 #必选 pod名称
  namespace: dev # pod所属命名空间 (默认 default)
  labels:
    label_ver: v1
    label_env: test
spec: #必选 pod中容器的规范
  containers: #必选,pod容器列表
    - name: nginx #必选，容器名
      image: test1:v1 #必选，容器镜像
  nodeName: node1
  #污点(容忍)调度
  tolerations:
    # 容忍任何key,任何value,任何effect
    - operator: Exists