apiVersion: v1 #必选
kind: Pod #必选
metadata: #必选
  name: mypod-demo1 #必选 pod名称
  namespace: dev # pod所属命名空间 (默认 default)
  labels:
    ver: snapshot-1.0
    env: test
spec: #必选 pod中容器的规范
  containers: #必选,pod容器列表
    - name: nginx #必选，容器名
      image: test1:v1 #必选，容器镜像
      imagePullPolicy: Never
      #command: ["sh","-l"]
      #args: ["hello", "world"]
      args: ["sh","/run.sh","hello","world"]
      env: #容器环境变量
        - name: JAVA_HOME #环境变量名称
          value: /root/jdk1.8.0_191 #环境变量值
        - name: JABA_PATH
          value: hello-world
      ports: #需要暴露的端口列表
        - name: nginx-prot #端口名
          containerPort: 80 #容器端口
          hostPort: 8888 #宿主机端口,不写则声明端口，写就是真实映射
          protocol: TCP #支持TCP/UDP,默认为TCP
    - name: busybox
      image:  test2:v2
      imagePullPolicy: Never
      args: ["sh","/run1.sh","hello","world"]
      ports: #需要暴露的端口列表
        - name: nginx-prot #端口名
          containerPort: 90 #容器端口
          hostPort: 9999 #宿主机端口,不写则声明端口，写就是真实映射
          protocol: TCP #支持TCP/UDP,默认为TCP