server:
  port: 9999
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
provider-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
#sp-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#xxxx-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  eager-load:
    enabled: true  #启动后立即加载feign客户端
    clients: provider-service


