server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2?useSSL=false
    username: root
    password: 123456
  application:
    name: sp-bb-service
  cloud:
    nacos:
      server-addr: 192.168.109.1:8848
seata:
  registry: #TC服务注册中心配置，微服务根据这些信息去注册中心获取TC服务地址
    type: nacos
    nacos: #tc
      server-addr: 192.168.109.1:8848
      namespace: ""
      group: DEFAULT_GROUP
      application: seata-tc-server
      username: nacos
      password: nacos
  tx-service-group: seata-name-demo #事务组名，根据这个获取TC服务的cluster名称
  service:
    vgroup-mapping: #与TC服务cluster的映射关系
      seata-name-demo: zjnacos
  data-source-proxy-mode: AT
logging:
  config: classpath:log4j2.xml