server:
  port: 8888
dubbo:
  application:
    name: consumer-zookeeper
    qos-enable: false
    qos-port: 3333
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://192.168.88.11:2181
