apiVersion: v1 #必选
kind: ConfigMap #必选
metadata: #必选
  name: configmap-name #必选 pod名称
  namespace: dev # pod所属命名空间 (默认 default)
  labels:
    ver: myv1
    env: test
data:
  filename: |
    username:admin
    helloworld
    password:123456
  filename2: |-
    username2:admin
    helloworld2
    password2:123456