server:
  port: 9999
spring:
  application:
    name: sp-gateway
  cloud:
    nacos:
      server-addr: 192.168.109.1:8848
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            # 允许携带认证信息
            # 允许跨域的源(网站域名/ip)，设置*为全部
            # 允许跨域请求里的head字段，设置*为全部
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            # 跨域允许的有效期
            allow-credentials: true
            allowed-origins:
              - "http://localhost:13009"
              - "http://localhost:13010"
            allowed-headers: "*"
            allowed-methods:
              - OPTIONS
              - GET
              - POST
            max-age: 3600
      routes: #网关配置
        - id: sp-a-service
          uri: lb://sp-a-service #lb可以实现服务的负载均衡  可以填写http:127.0.0.1:8080具体的地址
          predicates: #断言规则
            - Path=/a/**
          filters:
             - AddRequestHeader=tou5, xiaotou5
             - AddRequestHeader=tou6, xiaotou6
             - AddRequestHeader=tou, xiaotou
#            - StripPrefix=1 #过滤掉前缀 /a/
        - id: sp-b-service
          uri: lb://sp-b-service
          predicates:
            - Path=/b/**
#          filters:
#            - StripPrefix=1
      default-filters: #对所有的请求过滤生效也可以定义GlobalFilter，效果都说针对所有的服务做过滤
        - AddRequestHeader=tou1, daotou1
        - AddRequestHeader=tou2, daotou2
        - AddRequestHeader=tou3, daotou3
        - StripPrefix=1  # 1 2 3 4去掉前缀路径
        - AddRequestHeader=tou4, daotou4
        - AddRequestHeader=origin, gateway
sp-a-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  eager-load:
    enabled: true
    clients: sp-a-service
