apiVersion: v1
kind: Namespace
metadata:
  name: dev-ns

---

apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
  namespace: dev-ns
  labels:
    version: "1.0"
    env: "test"
spec:
  containers:
    - name: nginx-containers
      image: nginx:latest