apiVersion: v1 #必选
kind: Pod #必选
metadata: #必选
  name: pod-name #必选 pod名称
  namespace: dev # pod所属命名空间 (默认 default)
  labels:
    ver: myv1
    env: test
spec: #必选 pod中容器的规范
  containers: #必选,pod容器列表
    - name: nginx-name #必选，容器名
      image: nginx:1.14-alpine #必选，容器镜像
      volumeMounts:
        - name: log-volume
          mountPath: /var/log/nginx
    - name: busy-box-name #必选，容器名
      image: test:v1
      #必选，容器镜像
      volumeMounts:
        - name: log-volume
          mountPath: /data
      command: ["/bin/sh","-c","tail -f /data/access.log"]
  volumes: #声明数据卷
    - name: log-volume
      hostPath:
        path: /root/logs
        #"" 空字符串（默认）用于向后兼容，这意味着在安装 hostPath 卷之前不会执行任何检查。
        #DirectoryOrCreate	如果在给定路径上什么都不存在，那么将根据需要创建空目录，权限设置为 0755，具有与 kubelet 相同的组和属主信息。
        #Directory	在给定路径上必须存在的目录。
        #FileOrCreate	如果在给定路径上什么都不存在，那么将在那里根据需要创建空文件，权限设置为 0644，具有与 kubelet 相同的组和所有权。
        #File	在给定路径上必须存在的文件。
        #Socket	在给定路径上必须存在的 UNIX 套接字。
        #CharDevice	在给定路径上必须存在的字符设备。
        #BlockDevice	在给定路径上必须存在的块设备。
        type: DirectoryOrCreate
