apiVersion: v1 #必选
kind: Pod #必选
metadata: #必选
  name: pod-name #必选 pod名称
  namespace: dev # pod所属命名空间 (默认 default)
  labels:
    ver: myv1
    env: test
spec: #必选 pod中容器的规范
  containers: #必选,pod容器列表
    - name: nginx-name #必选，容器名
      image: nginx:1.14-alpine #必选，容器镜像
      volumeMounts:
        - name: log-volume
          mountPath: /var/log/nginx
    - name: busy-box-name #必选，容器名
      image: test:v1
      #必选，容器镜像
      volumeMounts:
        - name: log-volume
          mountPath: /data
      command: ["/bin/sh","-c","tail -f /data/access.log"]
  volumes: #声明数据卷
    - name: log-volume
      emptyDir: {}
