server:
  port: 9999
dubbo:
  application:
    name: provider-zookeeper
    qos-enable: false
    qos-port: 2222
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://192.168.88.11:2181

