apiVersion: v1 #必选
kind: Secret #必选
metadata: #必选
  name: secret-name #必选 pod名称
  namespace: dev # pod所属命名空间 (默认 default)
  labels:
    ver: myv1
    env: test
data:
  username: ZXJpYw== #值只能是base64编码类型的
  passwd: MTIzNDU2